### ISSUE TITLE
how to setup secondary ECU and get update through the primary ECU?

### ISSUE THREAD

**Issue by chen-sh-io** [uptane/aktualizr#103]
can you describe how to setup/configure the secondary ECU, communicate with the primary ECU and get update through the primary ECU?

**Comment by pattivacek** [comment]
The Here OTA docs are still mostly accurate, despite that they no longer offer the service. You can find the same docs in this repo but it's easier to read them on the website. :) See for example [here](https://docs.ota.here.com/ota-client/latest/libaktualizr-update-secondary.html).
