### ISSUE TITLE
RFC: Increase C++ version to C++17

### ISSUE THREAD

**Issue by cajun-rat** [uptane/aktualizr#106]
At the moment Aktualizr requires C++11 to build. I propose we bump that to C++17.

Full C++17 support came in [gcc 8](https://gcc.gnu.org/projects/cxx-status.html#cxx17) (although most of it was present in gcc 7 already. In terms of our likely target platforms already ship that:

* Debian oldstable [shipped with gcc-10](https://packages.debian.org/bullseye/gcc).
* The oldest supported Yocto release is [Dunfell](https://wiki.yoctoproject.org/wiki/Releases), which shipped [gcc 9.5](https://layers.openembedded.org/layerindex/recipe/121619/) 

That suggests that getting a C++17 compiler shouldn't be a huge problem for our downstream.

Why not go further?  C++20 support would require gcc 10 or 11, and while we _could_ go that far it seems like we should be conservative by default.

Comments welcome!

**Comment by pattivacek** [comment]
I'm on board. I remember when we made the decision to support C++11 five or six years ago!

**Comment by cajun-rat** [comment]
> I'm on board. I remember when we made the decision to support C++11 five or six years ago!
> 
> Edit: [found it](https://github.com/advancedtelematic/aktualizr/pull/514)! Not sure why I felt like looking it up, curiosity got the best of me.

Brings back good memories!

I've been working on a big series to remove the deprecated openssl functions, and I have this upgrade as a part of that at the moment. It is still WIP, but the (unstable) branch is [feat/openssl3](https://github.com/cajun-rat/aktualizr/commits/feat/openssl3/) on my github.  It is currently built on the Toradex fork, but I have another task to rebase that and bring it close to upstream.

**Comment by mike-sul** [comment]
> That suggests that getting a C++17 compiler shouldn't be a huge problem for our downstream.

That's not an issue for Foundries at all, we moved to `gcc 11.4` and clang `11.1` long time ago.

**Comment by mike-sul** [comment]
> Why not go further? C++20 support would require gcc 10 or 11, and while we _could_ go that far it seems like we should be conservative by default.

I would be conservative too, unless there are strong benefits in switching to `C++20`.

**Comment by cajun-rat** [comment]
Fixed!
