### ISSUE TITLE
Proposal: Dump PKCS#11 support, replace it with TPM support

### ISSUE THREAD

**Issue by tkfu** [uptane/aktualizr#122]
I was talking with @cajun-rat yesterday, and we were discussing how much of a PITA the PKCS#11 support is. Because libp11 is an openssl engine, it does not work with openssl 3, so we have to keep openssl 1.1.1 around for only this one feature. There doesn't appear to be a particularly mature pkcs#11 provider for openssl 3: https://github.com/latchset/pkcs11-provider seems to be the best available, but the current release is 0.5 and it looks to be more or less a one-man show, so I'm not sure about longevity.

However, hardware-backed signing is obviously important. We do have an alternative here, though: TPMs are widely available. On x86, of course, they're mandatory. On ARM, even though not every system builds in a discrete TPM, you can always bring in OP-TEE and run an fTPM as a trusted application.

https://github.com/tpm2-software/tpm2-openssl is a well-supported openssl3 provider API implementation for TPMs, maintained by the Trusted Computing Group. I'd like to propose ripping out pkcs#11 support entirely, and replacing it with TPM2 support.

@detsch and @doanac, you guys are the main other people who I believe may be actually using the PKCS#11 stuff. What are your thoughts?

**Comment by doanac** [comment]
Adding @mike-sul who's fought this a little as well as @ricardosalveti.

I can say that we have a lot of devices under management that use PKCS#11. A change would likely require a migration for us - and if it causes changes to things like sota.toml configuration ... it might be really tricky for production.

**Comment by ricardosalveti** [comment]
> A change would likely require a migration for us - and if it causes changes to things like sota.toml configuration

And it might not really be possible on some devices (since it requires a newer OP-TEE with and additional TA), besides requiring new keys and CSRs.

**Comment by ldts** [comment]
in case it helps framing the discussion https://docs.foundries.io/94/reference-manual/ota/ota-architecture.html#how-a-device-uses-security-hardware
